server:
  port: 8080

spring:
  application:
    name: api-gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Identity & Access
            - id: auth-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/auth/**

            # User Management
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**

            # Scheduling
            - id: scheduling-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/scheduling/**

