server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/MsAuthDB
    username: postgres
    password: postgre
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

user-management:
  url: http://localhost:8081

jwt:
  secret: ${JWT_SECRET:4f9a2b8c5d7e1f3a6b8d0c2e4f6a8b1c3d5e7f9a2b4c6d8e0f1a3b5c7d9e1f2a}
  access-expiration: 900000      # 15 min
  refresh-expiration: 604800000  # 7 días